### ISSUE TITLE
Package detail page not rendering properly: unsupported time zone error message

### ISSUE THREAD

**Issue by StephenKoller** [npm/www#346]
## Link to the page
[https://www.npmjs.com/package/moment-duration-format](https://www.npmjs.com/package/moment-duration-format) (or any package detail page)

## Logged in or logged out?
Logged out.

## Expected behavior
To see the package details page body rendered correctly.

## Actual behavior
I see a quick flash of styled content, and then this error appears, replacing the body of the page.

![image](https://user-images.githubusercontent.com/1561673/37772694-cd5b69f4-2db1-11e8-88c6-02704b781c48.png)

## Steps to reproduce the problem
1. Open Chrome 65 on Ubuntu 16.04
2. Go to [https://www.npmjs.com/package/moment-duration-format](https://www.npmjs.com/package/moment-duration-format)

## Browser with version
Chrome Version 65.0.3325.162 (Official Build) (64-bit)
on Ubuntu 16.04 LTS

Works fine in Firefox for Ubuntu 59.0.1 (64-bit)

## Any error message?
```javascript
raven.min.js:2 RangeError: Unsupported time zone specified undefined
    at new DateTimeFormat (native)
    at Date.toLocaleString (native)
    at ut.value (time.js:14)
    at Ms (react-dom.production.min.js:130)
    at beginWork (react-dom.production.min.js:133)
    at Os (react-dom.production.min.js:161)
    at Is (react-dom.production.min.js:161)
    at Rs (react-dom.production.min.js:162)
    at Ys (react-dom.production.min.js:169)
    at Ks (react-dom.production.min.js:168)
    at Bs (react-dom.production.min.js:167)
    at Hs (react-dom.production.min.js:165)
    at Object.updateContainer (react-dom.production.min.js:175)
    at react-dom.production.min.js:225
    at Object.unbatchedUpdates (react-dom.production.min.js:171)
    at To (react-dom.production.min.js:225)
    at Object.hydrate (react-dom.production.min.js:227)
    at render.js:13
pt.(anonymous function) @ raven.min.js:2
raven.min.js:2 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeChild (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:95618)
    at Rs (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:39397)
    at commitDeletion (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:41206)
    at Ns (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:45612)
    at Ys (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:51884)
    at Ks (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:51612)
    at Bs (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:50628)
    at Hs (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:49969)
    at Object.updateContainer (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:54645)
    at https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:66991
    at Object.unbatchedUpdates (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:53271)
    at To (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:66960)
    at Object.hydrate (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:97285)
    at https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:34:47817
pt.(anonymous function) @ raven.min.js:2
react-dom.production.min.js:222 Uncaught (in promise) DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeChild (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:95618)
    at Rs (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:39397)
    at commitDeletion (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:41206)
    at Ns (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:45612)
    at Ys (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:51884)
    at Ks (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:51612)
    at Bs (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:50628)
    at Hs (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:49969)
    at Object.updateContainer (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:54645)
    at https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:66991
    at Object.unbatchedUpdates (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:53271)
    at To (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:66960)
    at Object.hydrate (https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:30:97285)
    at https://static.npmjs.com/commons.53c278898e8b04ecf0ef.js:34:47817
/favicon.ico Failed to load resource: the server responded with a status of 404 ()
```

**Comment by jefflembeck** [comment]
I think we caught this one. We've tested in house and can't seem to repro. Please reopen if you still can.
