### ISSUE TITLE
Unsupported time zone error message when viewing package detail page

### ISSUE THREAD

**Issue by CharmedSatyr** [npm/www#354]
## Link to the page
https://www.npmjs.com/package/lodash

Note that this appears to be a broader issue with displaying package details, not specifically with the lodash page.

## Logged in or logged out?
Logged out

## Expected behavior
See package details page body rendered correctly.

## Actual behavior
There is a quick flash of styled content followed by this warning, which replaces the body of the page.
Presumably this is related to issue #346.

## Steps to reproduce the problem
1. Computer timezone is KST (Seoul, Korea, Republic of)
2. Open Chromium
3. Navigate to https://www.npmjs.com/package/lodash

## Browser with version
Chromium Version 64.0.3282.119 (Developer Build) built on Debian 9.3, running on Debian buster/sid (64-bit)

Works on Firefox 59.0.1

## Any error message?
```
RangeError: Unsupported time zone specified undefined
  at new DateTimeFormat (native)
    at Date.toLocaleString (native)
    at ut.value (https://static.npmjs.com/commons.381ecd0a49cec9f7f4f9.js:1:117131)
    at Ms (https://static.npmjs.com/commons.381ecd0a49cec9f7f4f9.js:30:31641)
    at beginWork (https://static.npmjs.com/commons.381ecd0a49cec9f7f4f9.js:30:33586)
    at Os (https://static.npmjs.com/commons.381ecd0a49cec9f7f4f9.js:30:47337)
    at Is (https://static.npmjs.com/commons.381ecd0a49cec9f7f4f9.js:30:47710)
    at Rs (https://static.npmjs.com/commons.381ecd0a49cec9f7f4f9.js:30:47983)
    at Ys (https://static.npmjs.com/commons.381ecd0a49cec9f7f4f9.js:30:51835)
    at Ks (https://static.npmjs.com/commons.381ecd0a49cec9f7f4f9.js:30:51612)
    at Bs (https://static.npmjs.com/commons.381ecd0a49cec9f7f4f9.js:30:50628)
    at Hs (https://static.npmjs.com/commons.381ecd0a49cec9f7f4f9.js:30:49969)
    at Object.updateContainer (https://static.npmjs.com/commons.381ecd0a49cec9f7f4f9.js:30:54645)
    at https://static.npmjs.com/commons.381ecd0a49cec9f7f4f9.js:30:66991
    at Object.unbatchedUpdates (https://static.npmjs.com/commons.381ecd0a49cec9f7f4f9.js:30:53271)
    at To (https://static.npmjs.com/commons.381ecd0a49cec9f7f4f9.js:30:66960)
    at Object.hydrate (https://static.npmjs.com/commons.381ecd0a49cec9f7f4f9.js:30:97285)
    at https://static.npmjs.com/commons.381ecd0a49cec9f7f4f9.js:34:47822
    at <anonymous>
```

**Comment by CharmedSatyr** [comment]
I am no longer experiencing this issue.

**Comment by hakeee** [comment]
I'm experiencing the same

## Steps to reproduce the problem
`timedatectl status` gives
```Local time: Tue 2018-05-29 17:30:26 CEST
Universal time: Tue 2018-05-29 15:30:26 UTC
RTC time: Tue 2018-05-29 15:30:26
Time zone: Europe/Prague (CEST, +0200)
System clock synchronized: yes
systemd-timesyncd.service active: yes
RTC in local TZ: no
```
Open Chromium
Navigate to https://www.npmjs.com/package/lodash
## Browser with version
Chromium  66.0.3359.181 (Official Build) Arch Linux (64-bit)
