### ISSUE TITLE
(SystemJS) XHR error (404 Not Found) 

### ISSUE THREAD

**Issue by NazarAliM** [npm/www#377]
## Steps to reproduce the problem
1. 

## Any error message?

**Comment by NazarAliM** [comment]
Hello every one 
I am a dot net developer new to Angular 2
I am trying to add a package to my angular application like ng2-bs3-modal & ng2-opd-popup.

I followed the steps as mentioned in the page https://www.npmjs.com/package/ng2-bs3-modal

I noticed when i run the application from the node.js using "ng serve" it is working fine but when i run it from visual studio it is giving systemjs error.
When I add the imports line in the app.module.ts the error came, it seems that from the visual studio the systemjs cannot find the files although it shows the right path.

Here is what i get:
CRIPT5009: SCRIPT5009: 'System' is not defined.

HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - http://localhost:5843/node_modules/ng2-bs3-modal.js

Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:5843/node_modules/ng2-bs3-modal.js
Error: XHR error (404 Not Found) loading http://localhost:5843/node_modules/ng2-bs3-modal.js
at wrapFn (http://localhost:5843/node_modules/zone.js/dist/zone.js:1188:5)
at ZoneDelegate.prototype.invokeTask (http://localhost:5843/node_modules/zone.js/dist/zone.js:419:13)
at Zone.prototype.runTask (http://localhost:5843/node_modules/zone.js/dist/zone.js:188:21)
at ZoneTask.invokeTask (http://localhost:5843/node_modules/zone.js/dist/zone.js:496:17)
at invokeTask (http://localhost:5843/node_modules/zone.js/dist/zone.js:1540:9)
at globalZoneAwareCallback (http://localhost:5843/node_modules/zone.js/dist/zone.js:1566:17)
Error loading http://localhost:5843/node_modules/ng2-bs3-modal.js as "ng2-bs3-modal" from http://localhost:5843/src/app/app.module.js

Any help or a try will be appreciated.

Thanks in advance.
